{% set name = "tams" %}
{% set version = "0.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/knubez/TAMS/archive/v{{ version }}.tar.gz
  sha256: afc14c7c144e1dd53802b07379b4de74e236377289d7bea1b5c73daabc29f20f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.7
    - pip
    - flit-core
  run:
    - python >=3.7
    #
    # Core dependencies
    - geopandas >=0.10
    - matplotlib-base >=3.4
    - numpy
    - pandas
    - scikit-image
    - shapely
    - xarray
    #
    # Extras
    - cartopy >=0.21
    - dask-core
    - gdown
    - joblib
    - netcdf4
    - pygeos
    - regionmask
    - scipy

test:
  imports:
    - tams

about:
  home: https://tams.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/knubez/TAMS
  doc_url: https://tams.readthedocs.io
  summary: TAMS (Tracking Algorithm for Mesoscale Convective Systems)

extra:
  recipe-maintainers:
    - zmoon
