{% set name = "tams" %}
{% set version = "0.1.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/knubez/TAMS/archive/v{{ version }}.tar.gz
  sha256: eeed9527ab9b0762f32366555dcea3d3ae29f0426352887a06787433b263e9c8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core
  run:
    - python >={{ python_min }}
    #
    # Core dependencies
    - geopandas >=0.10
    - matplotlib-base >=3.4
    - numpy
    - pandas
    - scikit-image
    - shapely
    - xarray
    #
    # Extras
    - cartopy >=0.21
    - dask-core
    - gdown
    - joblib
    - netcdf4
    - regionmask >=0.9
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - tams

about:
  home: https://tams.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/knubez/TAMS
  doc_url: https://tams.readthedocs.io
  summary: TAMS (Tracking Algorithm for Mesoscale Convective Systems)

extra:
  recipe-maintainers:
    - zmoon
